### PR TITLE
Reorganized the structure of ColorMania.py

### PR DESCRIPTION
**Pull request by siegelty**
This restructured how the level is handled by moving LevelScreens into the main loop under gamestate 0. 
1. Along with that, the final score etc. was changed with menu and quit buttons so the user can now decide whether to return to the menu or quit the game.
2. The way quits are now handled are through sending the game to gamestate -1, in there it will change the done variable to True. There and ONLY THERE should done be changed to help with handling the loop behavior.
3. I added two more graphics, the main menu graphic and the quit graphic, these can be found once Akshay uploads them to our repo, or though the email. Make sure they are titled MainMenu.png and QUIT.png.
4. LevelScreens now can return a number to be set to gamestate. This was used in our scenario to return when the player died or completed the level. In further iterations, we can have it return #x for a death and #y for a life just so we can eliminate the need to check if it is player.complete every time. However, we don't need to worry about that right now.

### CODE REVIEW

**Comment by siegelty** [comment]
Let me know if there are any questions, this should help you all visualize what I was getting at.

**Comment by akshayvk** [comment]
For some reason, I can't comment in your code. So I'm just going to put it here. When you call the function Level Screens, you must be going out of scope because player_tutorial is not defined and throwing an error. Also, we had a loop for managing player lives and checking to see when it hits zero. I think there may have been a change in the actual gameplay gamestate and the lives are automatically going down to zero and ending the game.

**Comment by siegelty** [comment]
Alright awesome thanks. And I meant to comment on it in this section.

Best,
Tyler Siegel
siegelty@umich.edu

**Comment by siegelty** [comment]
Just fixed the lives bug and tutorial but, creating a new function called reset which will reset it to 0,0

**Pull request merged**
